import { mkdirSync, readFileSync, readdirSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { logger } from "./logger.js";
import { thinkTool } from "../tools/think.js";

/**
 * Bridges CodeJet's tools into the OpenCode server.
 *
 * The OpenCode server runs its own agent loop with its own built-in tools, so
 * the schemas CodeJet sends on the chat-completions path do not exist there.
 * That is why an OpenCode model would report a tool list of apply_patch, bash,
 * edit, glob, grep, question, read, skill, todowrite, webfetch, websearch and
 * write — and no `think`.
 *
 * OpenCode loads custom tools from `~/.config/opencode/tools/`, one tool per
 * file, where the filename becomes the tool name. Critically, a custom tool
 * that shares a name with a built-in *replaces* the built-in. So writing tool
 * definition files there is the supported way both to add `think` and to
 * override OpenCode's own tools.
 *
 * Generated files are self-contained: they execute inside OpenCode's runtime,
 * not ours, so they cannot import CodeJet modules.
 */

/** Marks a file as ours. Files without it are never touched. */
const MANAGED_MARKER = "@codejet-managed";

/** Bump when generated output changes so existing files are refreshed. */
const GENERATION = 1;

export interface ProvisionResult {
  /** Tool names written or refreshed. */
  written: string[];
  /** Tools left alone because a user-owned file of the same name exists. */
  conflicts: string[];
  /** Already up to date. */
  unchanged: string[];
  /** Managed files removed because they are no longer wanted. */
  removed: string[];
  toolsDir: string;
  error?: string;
}

export function openCodeConfigDir(): string {
  // OpenCode uses XDG-style paths on every platform, including Windows.
  const override = process.env.OPENCODE_CONFIG_DIR;
  if (override && override.trim()) return override.trim();
  return join(homedir(), ".config", "opencode");
}

export function openCodeToolsDir(): string {
  return join(openCodeConfigDir(), "tools");
}

function header(name: string): string {
  return [
    "// ─────────────────────────────────────────────────────────────",
    `// ${MANAGED_MARKER} generation=${GENERATION} tool=${name}`,
    "//",
    "// Generated by CodeJet. Do not edit: this file is rewritten whenever",
    "// CodeJet starts the OpenCode server. Remove the marker line above to",
    "// take ownership of it and CodeJet will leave it alone.",
    "// ─────────────────────────────────────────────────────────────",
    "",
  ].join("\n");
}

/**
 * The `think` tool.
 *
 * Description is taken from the canonical ToolDefinition so the OpenCode-side
 * schema cannot drift from the chat-completions one. Execution is a no-op ack,
 * exactly as in the local implementation: think() exists so the model reasons
 * explicitly, not to move data around.
 */
function thinkToolSource(): string {
  const description = JSON.stringify(thinkTool.description);
  const thoughtDesc = JSON.stringify(
    "Your reasoning. Be concrete and specific: what you know, what you are unsure about, and why you are choosing a particular approach.",
  );
  const nextStepDesc = JSON.stringify(
    "Optional. The single concrete action you intend to take next.",
  );

  return `${header("think")}import { tool } from "@opencode-ai/plugin"

export default tool({
  description: ${description},
  args: {
    thought: tool.schema.string().describe(${thoughtDesc}),
    next_step: tool.schema.string().optional().describe(${nextStepDesc}),
  },
  async execute(args) {
    const thought = typeof args.thought === "string" ? args.thought.trim() : ""
    if (!thought) {
      return "No thought recorded — the \`thought\` parameter was empty. Provide your reasoning as a string."
    }
    return args.next_step
      ? "Thought recorded. Proceed with the next step."
      : "Thought recorded. Continue."
  },
})
`;
}

interface GeneratedTool {
  name: string;
  source: () => string;
  /** True when this replaces an OpenCode built-in of the same name. */
  overridesBuiltin: boolean;
}

const GENERATED_TOOLS: GeneratedTool[] = [
  { name: "think", source: thinkToolSource, overridesBuiltin: false },
];

function isManaged(contents: string): boolean {
  return contents.includes(MANAGED_MARKER);
}

/**
 * Writes CodeJet's tool definitions into the OpenCode tools directory.
 *
 * Idempotent: unchanged files are left untouched so the server does not see a
 * modification on every launch. Never overwrites a file the user owns.
 */
export function provisionOpenCodeTools(): ProvisionResult {
  const toolsDir = openCodeToolsDir();
  const result: ProvisionResult = {
    written: [],
    conflicts: [],
    unchanged: [],
    removed: [],
    toolsDir,
  };

  try {
    mkdirSync(toolsDir, { recursive: true });
  } catch (err) {
    result.error = `Could not create ${toolsDir}: ${err instanceof Error ? err.message : String(err)}`;
    logger.warn("opencode-tools", result.error);
    return result;
  }

  const wanted = new Set(GENERATED_TOOLS.map((t) => `${t.name}.ts`));

  for (const tool of GENERATED_TOOLS) {
    const file = join(toolsDir, `${tool.name}.ts`);
    const source = tool.source();

    try {
      if (existsSync(file)) {
        const existing = readFileSync(file, "utf-8");

        if (!isManaged(existing)) {
          // A user-authored tool of the same name wins. Overwriting someone's
          // own tool would be a surprising, destructive side effect.
          result.conflicts.push(tool.name);
          continue;
        }
        if (existing === source) {
          result.unchanged.push(tool.name);
          continue;
        }
      }

      writeFileSync(file, source, "utf-8");
      result.written.push(tool.name);
    } catch (err) {
      logger.warn(
        "opencode-tools",
        `Failed to write ${file}: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  // Clean up managed files we no longer generate, so removing a tool from
  // CodeJet actually removes it from OpenCode too.
  try {
    for (const entry of readdirSync(toolsDir)) {
      if (!entry.endsWith(".ts") || wanted.has(entry)) continue;
      const file = join(toolsDir, entry);
      try {
        if (isManaged(readFileSync(file, "utf-8"))) {
          rmSync(file);
          result.removed.push(entry.replace(/\.ts$/, ""));
        }
      } catch {
        // Unreadable entry: leave it alone.
      }
    }
  } catch {
    // Directory listing failed; provisioning still succeeded.
  }

  const summary = [
    result.written.length ? `written: ${result.written.join(", ")}` : "",
    result.unchanged.length ? `unchanged: ${result.unchanged.join(", ")}` : "",
    result.conflicts.length ? `user-owned: ${result.conflicts.join(", ")}` : "",
    result.removed.length ? `removed: ${result.removed.join(", ")}` : "",
  ]
    .filter(Boolean)
    .join("  ");

  logger.info("opencode-tools", `Provisioned ${toolsDir}  ${summary}`);
  return result;
}

/** Tool names CodeJet guarantees are available on the OpenCode path. */
export function provisionedToolNames(): string[] {
  return GENERATED_TOOLS.map((t) => t.name);
}

/** True when provisioning changed anything, meaning a running server is stale. */
export function requiresServerRestart(result: ProvisionResult): boolean {
  return result.written.length > 0 || result.removed.length > 0;
}
